### ISSUE TITLE
Can't understand the design of Δfi

### ISSUE THREAD

**Issue by wqfdewifi** [w1oves/Rein#25]
Sorry for my poor comprehension ability, I cant understand the design of this  ![image](https://github.com/w1oves/Rein/assets/54132689/8e3651f5-b0ff-45e9-ab35-0f6cccd07e31) , even though I've read the paper many times. I'm curious if removing the the first column of Si and first row of Ti achieves the same result as removing any column of Si and any row of Ti. I can't understand why it has to be the first one. 

I'd appreciate it if you could explain it to me.

**Comment by w1oves** [comment]
Thank you for your interest in my work! I apologize for any confusion caused by my unclear explanation, wasting your time. Removing any column can achieve a result similar to removing the first column; I merely chose the first column as it was the easiest option. The key is to remove one column so that the total sum of the similarity matrix S does not equal 1. This idea was inspired by [Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588). If you have any further questions, please feel free to ask.

**Comment by wqfdewifi** [comment]
I'm clear now, thank you！
