### ISSUE TITLE
How to understand S_i(:,2:m) in eq6?

### ISSUE THREAD

**Issue by ljjcoder** [w1oves/Rein#59]
Thanks for your excellent work, I have a question, why did you remove the first column in si to calculate \delta f?

**Comment by w1oves** [comment]
- The application of softmax ensures that the similarity of each row sums to 1.
- Some features do not need modification, meaning they are dissimilar to every token; in such cases, it would be reasonable for the total similarity of that row to be lower.
- After removing a token, the similarity for each row can range from 0 to 1.
- Removing any column can achieve a result similar to removing the first column; I merely chose the first column as it was the easiest option. The key is to remove one column so that the total sum of the similarity matrix S does not equal 1. This idea was inspired by [Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588). If you still have any further questions, please feel free to ask.

**Comment by w1oves** [comment]
Thank you very much for your support of Rein! If this project or my answer is helpful to you, please give me a star, which is very important to me. If you have any further questions, please feel free to ask.

**Comment by ljjcoder** [comment]
@w1oves Thanks for your reply. Based on your answer, I found the answer I wanted in Vision Transformers Need Registers. A small suggestion is that you can mention the idea of ​​Vision Transformers Need Registers after eq6, which will make it much easier to understand.

**Comment by w1oves** [comment]
Thank you for your suggestion! I will updated it in the arxiv version.
