### ISSUE TITLE
Checkpoints and config files for high-resolution testing in Rein models

### ISSUE THREAD

**Issue by ysj9909** [w1oves/Rein#68]
Hello,

First of all, I would like to express my gratitude for providing this amazing codebase, which has been instrumental in conducting my experiments. While working on my research, I came across an interesting observation in your code. Specifically, I noticed a significant performance improvement when resizing to (2048, 1024) instead of (1024, 512) in the test_pipeline. For instance, in the GTAV -> Cityscapes, BDD, and Map setting, the average performance of Rein improved from 64.3 to 66.09.

To ensure a fair comparison in my work, I plan to report the performance of all Rein models measured at higher resolutions during the test phase.

So, I would like to request some checkpoints and config files that are not yet available in the repository. Specifically, I need the files for the experiments shown in Table 7, Table 16, and Table 14 (DINOv2, EVA02-L results). Additionally, it seems that the checkpoint and config files for the model trained with GTAV + Synthia + UrbanSyn as source domains at a 1024x1024 resolution might have been incorrectly uploaded. I would appreciate it if you could provide the correct versions of those as well.

Receiving these checkpoint and config files would greatly benefit my research. Lastly, thank you once again for your inspiring research and for sharing such a helpful codebase.

**Comment by w1oves** [comment]
Thank you for your attention and detailed observations! Some experiments were conducted on an earlier version of the code, which was quite messy. I have since cleaned up the code and released the current version. Reorganizing some results and conducting high-resolution experiments is time-consuming, and I apologize for my busy schedule. I recommend using your reproduced experiments for your paper. Here are the results I can provide:

| Experiment                | Resolution     | Configuration Link | Weight Link | Log Link | Cityscapes mIoU | BDD mIoU | Map mIoU|
|---------------------------|----------------|---------------------|-------------|----------|-----------------|----------|------|
| DINOV2+Rein in TABLE 7    | 2560 & 2048    | [c2bm_cfg.py](https://github.com/w1oves/Rein/releases/download/to-bdd-map/c2bm_cfg.py) | [citys2acdc_40k_rein_head.pth](https://github.com/w1oves/Rein/releases/download/Cityscapes/citys2acdc_40k_rein_head.pth) | [c2bm_log.json](https://github.com/w1oves/Rein/releases/download/to-bdd-map/c2bm_log.json) | 66.5            | 75.2    | -    |
| DINOv2+Rein in TABLE 16   | 2048 & 2560 & 2048 | [sg2cbm_cfg.py](https://github.com/w1oves/Rein/releases/download/to-bdd-map/sg2cbm_cfg.py) | [sg2cbm_weight.pth](https://github.com/w1oves/Rein/releases/download/to-bdd-map/sg2cbm_weight.pth) | [sg2cbm_log.json](https://github.com/w1oves/Rein/releases/download/to-bdd-map/sg2cbm_log.json) | 72.2            | 61.5    | 70.7 |
| GTAV + Synthia + UrbanSyn | 2048 & 2560 & 2048 | [usg2cbm_cfg.py](https://github.com/w1oves/Rein/releases/download/to-bdd-map/usg2cbm_cfg.py) | [usg2cbm_weight.pth](https://github.com/w1oves/Rein/releases/download/to-bdd-map/usg2cbm_weight.pth) | [usg2cbm_log.json](https://github.com/w1oves/Rein/releases/download/to-bdd-map/usg2cbm_log.json) | 78.4            | 62.2    | 74.5 |

For semFPN, I have not conducted high-resolution experiments. However, I have uploaded the low-resolution configuration, log, and weight files:

- [dinov2_semfpn_weight.pth](https://github.com/w1oves/Rein/releases/download/to-bdd-map/dinov2_semfpn_weight.pth)
- [dinov2_semfpn_log.json](https://github.com/w1oves/Rein/releases/download/to-bdd-map/dinov2_semfpn_log.json)
- [dinov2_semfpn_cfg.py](https://github.com/w1oves/Rein/releases/download/to-bdd-map/dinov2_semfpn_cfg.py)

I hope this reply helps you!

**Comment by ysj9909** [comment]
Thank you so much for taking the time to respond. It was very helpful!
