### ISSUE TITLE
the results of rein+clip

### ISSUE THREAD

**Issue by wqfdewifi** [w1oves/Rein#69]
Hello，sorry to bother you.     I used the config file of rein+clip that you released，but i couldn't reproduce the results presented in the paper (Table2, mIOU, Avg.57.4).  My reproduction result is around 54.2.   Besides, I also downloaded the log file that you released，the final results are：
"citys_aAcc": 91.24, "citys_mIoU": 58.05, "citys_mAcc": 72.86, "bdd_aAcc": 87.85, "bdd_mIoU": 49.26, "bdd_mAcc": 60.0, "map_aAcc": 91.01, "map_mIoU": 60.22, "map_mAcc": 73.97, "mean_aAcc": 90.03333333333332, "mean_mIoU": 55.843333333333334, "mean_mAcc": 68.94333333333334, "data_time": 0.003698470353467299, "time": 1.1512585241295412, "step": 40000}.

The mIOU is 55.84, which is not consistent with the paper. 
 
Could you please tell me how to reproduce the results of rein+clip reported in the paper?

**Comment by w1oves** [comment]
Thank you for your interest in our work on rein! [The original experiment for CLIP](https://github.com/w1oves/Rein/releases/download/GTAV%2BCLIP-L(1080)/early_log.json) were conducted during the early phases of the project and are not entirely applicable to the current version. The configuration and weights mentioned in the README are from my re-implemented version, which shows higher performance on the Cityscapes dataset, which has been my main focus.

However, understanding that you are interested in achieving a high mean mIoU, I retrained CLIP using a slightly different configuration. The only modification was changing the input resolution from 512 to 1080 in the training pipeline, while keeping the test pipeline unchanged. This adjustment results in a higher mean mIoU of 57.47, consistent with the paper, though it leads to a lower mIoU on Cityscapes. This is why I opted to use a 512 version in the README.

I apologize for any confusion caused by the changes across multiple code versions. Thank you for your understanding.
Results:
|Version|citys|bdd|map|mean|
|---|---|---|---|---|
|paper|57.1|54.7|60.5|57.4|
|readme(512)|58.1|49.3|60.2|55.8|
|this(1080)|57.2|55.0|60.2|57.5|

Config: https://github.com/w1oves/Rein/releases/download/GTAV%2BCLIP-L(1080)/rein_clip_cfg.py
Weight: https://github.com/w1oves/Rein/releases/download/GTAV%2BCLIP-L(1080)/rein_clip_weight.pth
Log: https://github.com/w1oves/Rein/releases/download/GTAV%2BCLIP-L(1080)/rein_clip_log.json

**Comment by wqfdewifi** [comment]
Thank you for your time ：）. This really helped me a lot.
