### ISSUE TITLE
about Table 1.

### ISSUE THREAD

**Issue by geyanqi** [w1oves/Rein#7]
Awesome work but a little issue. Is it possible to release the code of "Frozen backbone of VFMs"?  I'm very interested in how you can achieve such high segmentation performance with these functionally different backbones (SAM, MAE, and CLIP) by only training the decoder.

Best.

**Comment by w1oves** [comment]
Thank you very much for your attention! This is not a core contribution point in our work; adapting different VFMs is a simple yet laborious task. Due to my intense schedule over the past few days, I am currently unable to release code related to multiple frozen VFMs. However, I will endeavor to make the code regarding the frozen DINOv2 available as soon as possible. Your attention is greatly appreciated!



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/01/2024 12:35 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [w1oves/Rein] about Table 1. (Issue #7) |

Awesome work but a little issue. Is it possible to release the code of "Frozen backbone of VFMs" in the Table1? I'm very curious about how you can convert these frozen and different functional backbones through only training a decoder to achieve such high performance.

Best.

**Comment by geyanqi** [comment]
Thanks for your response, but I'd really like to learn how to adapt SAM and CLIP. Hope you will consider posting when you have time.

**Comment by w1oves** [comment]
Regarding SAM and CLIP, we merely extract their backbones and then combine them with a trainable Mask2Former.

**Comment by geyanqi** [comment]
Yes, but in my previous attempts, I got poor results. So I really want to learn your code 😂.

**Comment by w1oves** [comment]
You might need to interpolate the position encoding.

**Comment by geyanqi** [comment]
i will try it

**Comment by w1oves** [comment]
> i will try it

Hi! I've updated the code for training Frozen CLIP-L in configs/frozen_vfms.

**Comment by geyanqi** [comment]
thank you for your reply.

**Comment by geyanqi** [comment]
Hi, the "CLIPVisionTransformer" doesn't seem to be registered in backbone file.

**Comment by w1oves** [comment]
It should be okay now. Happy New Year!

**Comment by Stark320** [comment]
Could you please release the code for training Frozen SAM? Thanks a lot!
