### ISSUE TITLE
Lightweight Model with High Inference Speed

### ISSUE THREAD

**Issue by MMarvasti** [w1oves/Rein#77]
Hello @w1oves 

Thank you for sharing your impressive work.

I am interested in your insights on achieving **high inference speed** while maintaining acceptable accuracy for a **lightweight model**.

Based on your experience, could you recommend strategies to achieve this?

**Comment by w1oves** [comment]
Sorry, I haven't delved into lightweight design and fast inference. Based on my limited knowledge, I can offer the following suggestions:

1. **Parallelize VFM and Rein layers:** Currently, the i-th layer of VFMs and Reins seem to be serial: `result = VFMs[i](Reins[i](x) + x)`. Modifying this to a parallel structure: `result = VFMs[i](x) + Reins[i](x)` might improve speed, but the gain might not be significant.

2. **Utilize smaller VFMs:** Consider using smaller VFMs directly or distilling knowledge from larger VFMs to smaller ones. This can reduce computational complexity.

3. **Explore alternative architectures:** Instead of Mask2Former, investigate using architectures like SemFPN, which might offer better performance characteristics for your use case.

Please note that these are just general suggestions, and the optimal approach will depend on the specifics of your model and application.

**Comment by MMarvasti** [comment]
Thank you for your suggestions. Could you provide guidance on the necessary modifications for using smaller VFMs, such as DINOv2 Base or Small?

**Comment by w1oves** [comment]
Last week.

**Comment by MMarvasti** [comment]
Solved.!
